env: grf

env_args:
  dense_reward: False
  write_full_episode_dumps: False
  write_goal_dumps: False
  dump_freq: 1000
  render: False
  time_step: 0
  map_name: "academy_3_vs_1_with_keeper"
  stacked: False
  representation: "simple115"
  rewards: "scoring"
  logdir: "football_dumps"
  write_video: False
  number_of_right_players_agent_controls: 0
  seed: null

test_greedy: True
test_nepisode: 16
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
